import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { Plus, Pencil, Trash2, X, TrendingUp, ArrowRight } from 'lucide-react';
import clsx from 'clsx';

// Recent Products Form Component
export const RecentProductForm = ({ product, categories, vendors, onSave, onCancel, saving, allProducts = [], recentProducts = [] }) => {
    const [form, setForm] = useState(product || {
        productId: '',
        productName: '',
        category: categories[0] || 'SNACKS',
        vendorId: '',
        unitCost: '',
        mrp: '',
        quantity: '',
        units: 1,
        gst: 0.05,
        eanNo: '',
        selfLife: '',
        unitsPurchased: 0,
        unitsSold: 0
    });
    const [idError, setIdError] = useState('');
    const [isAutoGenerated, setIsAutoGenerated] = useState(!product);

    // Helper function to generate Product ID from name (checking both tables)
    const generateProductId = (productName) => {
        if (!productName || productName.trim().length < 3) return '';
        
        // Get first 4 characters (uppercase)
        const prefix = productName.trim().substring(0, 4).toUpperCase().replace(/[^A-Z0-9]/g, '');
        
        if (!prefix) return '';
        
        // Find all products with this prefix from both tables
        const matchingProducts = [
            ...allProducts.filter(p => 
                p.Product_ID && p.Product_ID.substring(0, prefix.length).toUpperCase() === prefix
            ),
            ...recentProducts.filter(p => 
                p.productId && p.productId.substring(0, prefix.length).toUpperCase() === prefix
            )
        ];
        
        // Get the highest sequence number
        let maxSeq = 0;
        matchingProducts.forEach(p => {
            const id = p.Product_ID || p.productId;
            const match = id.match(/(\d+)$/);
            if (match) {
                const seq = parseInt(match[1], 10);
                if (seq > maxSeq) maxSeq = seq;
            }
        });
        
        // Generate new ID with next sequence number
        const nextSeq = String(maxSeq + 1).padStart(3, '0');
        return `${prefix}${nextSeq}`;
    };

    const handleProductNameChange = (newName) => {
        setForm({ ...form, productName: newName });
        
        // Auto-generate ID only if it's a new product (not editing)
        if (!product) {
            const generatedId = generateProductId(newName);
            if (generatedId) {
                setForm(prevForm => ({ ...prevForm, productId: generatedId }));
                setIsAutoGenerated(true);
                setIdError('');
            }
        }
    };

    const handleProductIdChange = (newId) => {
        setForm({ ...form, productId: newId });
        setIsAutoGenerated(false);
        
        // Validate if ID already exists (skip for editing)
        if (!product && newId) {
            const exists = [
                ...allProducts,
                ...recentProducts
            ].some(p => 
                (p.Product_ID || p.productId) && (p.Product_ID || p.productId).toUpperCase() === newId.toUpperCase()
            );
            
            if (exists) {
                setIdError('This product id already exists');
            } else {
                setIdError('');
            }
        }
    };

    const handleChange = (field, value) => {
        setForm({ ...form, [field]: value });
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        
        if (!form.productId?.trim()) {
            alert('Please enter product ID');
            return;
        }

        if (idError) {
            alert(idError);
            return;
        }

        if (!form.productName?.trim()) {
            alert('Please enter product name');
            return;
        }

        if (!form.vendorId) {
            alert('Please select a vendor');
            return;
        }

        const gstValue = parseFloat(form.gst) || 0;
        
        onSave({
            ...form,
            productId: form.productId.trim(),
            productName: form.productName.trim(),
            unitCost: parseFloat(form.unitCost) || 0,
            mrp: parseFloat(form.mrp) || 0,
            quantity: form.quantity || '',  // Keep as string, not number
            units: parseInt(form.units) || 1,
            gst: gstValue > 1 ? gstValue / 100 : gstValue,
            selfLife: parseInt(form.selfLife) || 0,
            unitsPurchased: parseInt(form.unitsPurchased) || 0,
            unitsSold: parseInt(form.unitsSold) || 0
        });
    };

    return (
        <form onSubmit={handleSubmit} className="space-y-4 max-h-[70vh] overflow-y-auto">
            <div className="grid grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Product ID * {isAutoGenerated && <span className="text-xs text-orange-600">(Auto-generated)</span>}</label>
                    <input
                        type="text"
                        value={form.productId}
                        onChange={e => handleProductIdChange(e.target.value)}
                        className={clsx(
                            "w-full px-3 py-2 border rounded-lg text-sm focus:outline-none transition-colors",
                            idError 
                                ? "border-red-500 bg-red-50 focus:border-red-500" 
                                : isAutoGenerated
                                    ? "border-green-500 bg-green-50 focus:border-green-500"
                                    : "border-slate-200 focus:border-orange-500"
                        )}
                        placeholder="e.g., SAMP001"
                        required
                        disabled={!!product}
                    />
                    {idError && <span className="text-xs text-red-600 mt-1">{idError}</span>}
                    {isAutoGenerated && !idError && <span className="text-xs text-green-600 mt-1">Auto-generated based on product name</span>}
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Product Name *</label>
                    <input
                        type="text"
                        value={form.productName}
                        onChange={e => handleProductNameChange(e.target.value)}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                        placeholder="e.g., LAYS SALT"
                        required
                    />
                </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Category</label>
                    <input
                        type="text"
                        value={form.category}
                        onChange={e => handleChange('category', e.target.value.toUpperCase())}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500 uppercase"
                        placeholder="e.g., SNACKS, BEVERAGES"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Vendor *</label>
                    <select
                        value={form.vendorId}
                        onChange={e => handleChange('vendorId', e.target.value)}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                        required
                    >
                        <option value="">Select Vendor...</option>
                        {vendors.map(v => (
                            <option key={v.vendorId || v.Vendor_ID} value={v.vendorId || v.Vendor_ID}>
                                {v.vendorName || v.Name || v.VENDOR || v.Vendor_ID}
                            </option>
                        ))}
                    </select>
                </div>
            </div>

            <div className="grid grid-cols-3 gap-4">
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Unit Cost (₹) *</label>
                    <input
                        type="number"
                        step="0.01"
                        value={form.unitCost}
                        onChange={e => handleChange('unitCost', e.target.value)}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                        placeholder="0.00"
                        required
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">MRP (₹)</label>
                    <input
                        type="number"
                        step="0.01"
                        value={form.mrp}
                        onChange={e => handleChange('mrp', e.target.value)}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                        placeholder="0.00"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">GST %</label>
                    <input
                        type="number"
                        step="0.01"
                        value={form.gst}
                        onChange={e => handleChange('gst', e.target.value)}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                        placeholder="5"
                    />
                </div>
            </div>

            <div className="grid grid-cols-3 gap-4">
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Quantity</label>
                    <input
                        type="text"
                        value={form.quantity}
                        onChange={e => handleChange('quantity', e.target.value)}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                        placeholder="0"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Units/Case</label>
                    <input
                        type="number"
                        value={form.units}
                        onChange={e => handleChange('units', e.target.value)}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                        min="1"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Self Life (Months)</label>
                    <input
                        type="number"
                        value={form.selfLife}
                        onChange={e => handleChange('selfLife', e.target.value)}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                        placeholder="0"
                    />
                </div>
            </div>

            <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">EAN Number</label>
                <input
                    type="text"
                    value={form.eanNo}
                    onChange={e => handleChange('eanNo', e.target.value)}
                    className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                    placeholder="e.g., 8901234567890"
                />
            </div>

            <div className="grid grid-cols-2 gap-4 bg-blue-50 p-4 rounded-lg border border-blue-200">
                <div>
                    <label className="block text-xs text-blue-600 font-medium mb-1">Units Purchased</label>
                    <div className="text-lg font-bold text-blue-800">{parseInt(form.unitsPurchased) || 0}</div>
                    <div className="text-xs text-blue-600">Auto-tracked from deliveries</div>
                </div>
                <div>
                    <label className="block text-xs text-blue-600 font-medium mb-1">Units Sold</label>
                    <div className="text-lg font-bold text-blue-800">{parseInt(form.unitsSold) || 0}</div>
                    <div className="text-xs text-blue-600">Auto-tracked from batches</div>
                </div>
            </div>

            <div className="flex gap-3 pt-2">
                <button
                    type="button"
                    onClick={onCancel}
                    className="flex-1 px-4 py-2 border border-slate-200 rounded-lg text-slate-600 hover:bg-slate-50 text-sm font-medium"
                    disabled={saving}
                >
                    Cancel
                </button>
                <button
                    type="submit"
                    className="flex-1 px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded-lg text-sm font-medium disabled:opacity-50"
                    disabled={saving}
                >
                    {saving ? 'Saving...' : product ? 'Update Product' : 'Add Product'}
                </button>
            </div>
        </form>
    );
};

// Recent Products Table Component
export const RecentProductsTable = ({ products, onEdit, onDelete, onMove, loading, monthFilter, onMonthFilterChange }) => {
    const { hasPermission } = useAuth();
    if (loading) {
        return <div className="px-6 py-12 text-center text-slate-400">Loading recent products...</div>;
    }

    if (!products || products.length === 0) {
        return <div className="px-6 py-12 text-center text-slate-400">No recent products found. Add your first recent product to track sales performance.</div>;
    }

    // Calculate product age and check for 1-month notification
    const getProductAge = (createdAt) => {
        const now = new Date();
        const productDate = new Date(createdAt || Date.now());
        const ageInDays = (now - productDate) / (1000 * 60 * 60 * 24);
        const ageInMonths = ageInDays / 30;
        return { ageInDays, ageInMonths };
    };

    // Get products that exist for 1 month (for notifications)
    const productsOver1Month = products.filter(p => {
        const { ageInMonths } = getProductAge(p.createdAt || p.dateAdded || p.creationDate);
        return ageInMonths >= 1;
    });

    return (
        <div className="space-y-4">
            {/* 1-Month Notification Alert */}
            {productsOver1Month.length > 0 && (
                <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
                    <div className="flex items-start gap-3">
                        <div className="text-amber-600 font-semibold">📢 Products Active for 1+ Months</div>
                        <div className="flex-1 text-sm text-amber-700">
                            {productsOver1Month.map(p => {
                                const { ageInMonths } = getProductAge(p.createdAt || p.dateAdded || p.creationDate);
                                return (
                                    <div key={p.recentProductId || p.productId} className="flex justify-between items-center py-1">
                                        <span>{p.productName} - Rate: {p.rate?.toFixed(1) || 0}%</span>
                                        <span className="text-xs text-amber-600 font-medium">{ageInMonths.toFixed(1)} months</span>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                </div>
            )}

            <div className="overflow-x-auto">
                <table className="w-full">
                    <thead className="bg-slate-50 border-b border-slate-200">
                    <tr>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Product Name</th>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Category</th>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Vendor ID</th>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Unit Cost</th>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Quantity</th>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Units/Case</th>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Self Life</th>
                        <th className="px-6 py-3 text-center text-xs font-semibold text-slate-600 uppercase">Purchased</th>
                        <th className="px-6 py-3 text-center text-xs font-semibold text-slate-600 uppercase">Sold</th>
                        <th className="px-6 py-3 text-center text-xs font-semibold text-slate-600 uppercase">Rate %</th>
                        <th className="px-6 py-3 text-center text-xs font-semibold text-slate-600 uppercase">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {products.map((product, idx) => {
                        const rate = product.rate || 0;
                        const rateColor = rate > 80 ? 'text-red-600' : rate > 50 ? 'text-orange-600' : 'text-green-600';
                        const quantity = parseInt(product.quantity) || 0;
                        const unitCost = parseFloat(product.unitCost) || 0;
                        const unitCase = parseInt(product.units) || 1;
                        const selfLife = parseInt(product.selfLife) || 0;
                        const totalValue = quantity * unitCost;
                        
                        return (
                            <tr key={product.recentProductId || idx} className="border-b border-slate-50 hover:bg-slate-50/50">
                                <td className="px-6 py-4 font-medium text-slate-700">
                                    <div>{product.productName || '-'}</div>
                                    <div className="text-xs text-slate-400">{product.productId || '-'}</div>
                                </td>
                                <td className="px-6 py-4 text-slate-600">
                                    <span className="bg-blue-50 text-blue-600 px-2 py-1 rounded text-xs font-medium">
                                        {product.category || '-'}
                                    </span>
                                </td>
                                <td className="px-6 py-4 text-slate-600">{product.vendorId || '-'}</td>
                                <td className="px-6 py-4 text-slate-600">₹{unitCost.toFixed(2)}</td>
                                <td className="px-6 py-4 text-slate-600">{quantity}</td>
                                <td className="px-6 py-4 text-slate-600">{unitCase}</td>
                                <td className="px-6 py-4 text-slate-600">{selfLife} months</td>
                                <td className="px-6 py-4 text-center text-slate-600">{product.unitsPurchased || 0}</td>
                                <td className="px-6 py-4 text-center text-slate-600">{product.unitsSold || 0}</td>
                                <td className={`px-6 py-4 text-center font-semibold ${rateColor} flex items-center justify-center gap-1`}>
                                    <TrendingUp size={14} /> {rate.toFixed(1)}%
                                </td>
                                <td className="px-6 py-4">
                                    <div className="flex justify-center gap-2">
                                        {onMove && hasPermission('create_product') && (
                                            <button
                                                onClick={() => onMove(product)}
                                                className="text-green-600 hover:text-green-800 text-sm font-medium flex items-center gap-1 whitespace-nowrap"
                                                title="Move to Product Master"
                                            >
                                                <ArrowRight size={14} />
                                                Move to Master
                                            </button>
                                        )}
                                        {hasPermission('edit_product') && (
                                            <button
                                                onClick={() => onEdit(product)}
                                                className="text-blue-500 hover:text-blue-700 text-sm font-medium"
                                                title="Edit"
                                            >
                                                Edit
                                            </button>
                                        )}
                                        {hasPermission('delete_product') && (
                                            <button
                                                onClick={() => onDelete(product)}
                                                className="text-red-500 hover:text-red-700 text-sm font-medium"
                                                title="Delete"
                                            >
                                                Delete
                                            </button>
                                        )}
                                    </div>
                                </td>
                            </tr>
                        );
                    })}
                </tbody>
            </table>
        </div>
        </div>
    );
};
