import React, { useState } from 'react';
import { X, Phone, Mail, MapPin, Building } from 'lucide-react';
import clsx from 'clsx';

// Vendor Form Component for adding/editing vendors
export const VendorForm = ({ vendor, onSave, onCancel, existingVendors = [], saving }) => {
    const [form, setForm] = useState(vendor || {
        vendorId: '',
        vendorName: '',
        mobileNumber: '',
        email: '',
        gstNo: '',
        address: '',
        secondaryNumber: ''
    });
    const [idError, setIdError] = useState('');
    const [isAutoGenerated, setIsAutoGenerated] = useState(!vendor);

    // Helper function to generate Vendor ID from name (first character of each word)
    const generateVendorId = (vendorName) => {
        if (!vendorName || vendorName.trim().length < 1) return '';
        
        // Split by spaces and get first character of each word
        const words = vendorName.trim().split(/\s+/).filter(word => word.length > 0);
        const prefix = words.map(word => word[0]).join('').toUpperCase().replace(/[^A-Z0-9]/g, '');
        
        if (!prefix) return '';
        
        // Find all vendors with this prefix
        const matchingVendors = existingVendors.filter(v => 
            v.vendorId && v.vendorId.substring(0, prefix.length).toUpperCase() === prefix
        );
        
        // Get the highest sequence number
        let maxSeq = 0;
        matchingVendors.forEach(v => {
            const match = v.vendorId.match(/(\d+)$/);
            if (match) {
                const seq = parseInt(match[1], 10);
                if (seq > maxSeq) maxSeq = seq;
            }
        });
        
        // Generate new ID with next sequence number
        const nextSeq = String(maxSeq + 1).padStart(3, '0');
        return `${prefix}${nextSeq}`;
    };

    const handleVendorNameChange = (newName) => {
        setForm({ ...form, vendorName: newName });
        
        // Auto-generate ID only if it's a new vendor (not editing)
        if (!vendor) {
            const generatedId = generateVendorId(newName);
            if (generatedId) {
                setForm(prevForm => ({ ...prevForm, vendorId: generatedId }));
                setIsAutoGenerated(true);
                setIdError('');
            }
        }
    };

    const handleVendorIdChange = (newId) => {
        setForm({ ...form, vendorId: newId });
        setIsAutoGenerated(false);
        
        // Validate if ID already exists (skip for editing)
        if (!vendor && newId) {
            const exists = existingVendors.some(v => 
                v.vendorId && v.vendorId.toUpperCase() === newId.toUpperCase()
            );
            
            if (exists) {
                setIdError('This vendor id already exists');
            } else {
                setIdError('');
            }
        }
    };

    const handleChange = (field, value) => {
        setForm({ ...form, [field]: value });
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        
        if (!form.vendorName?.trim()) {
            alert('Please enter vendor name');
            return;
        }
        
        if (!form.mobileNumber?.trim()) {
            alert('Please enter mobile number');
            return;
        }

        if (!form.vendorId) {
            alert('Vendor ID is required');
            return;
        }

        if (idError) {
            alert(idError);
            return;
        }

        onSave({
            ...form,
            vendorName: form.vendorName.trim(),
            mobileNumber: form.mobileNumber.trim()
        });
    };

    return (
        <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Vendor ID * {isAutoGenerated && <span className="text-xs text-orange-600">(Auto-generated)</span>}</label>
                    <input
                        type="text"
                        value={form.vendorId}
                        onChange={e => handleVendorIdChange(e.target.value)}
                        className={clsx(
                            "w-full px-3 py-2 border rounded-lg text-sm focus:outline-none transition-colors",
                            idError 
                                ? "border-red-500 bg-red-50 focus:border-red-500" 
                                : isAutoGenerated
                                    ? "border-green-500 bg-green-50 focus:border-green-500"
                                    : "border-slate-200 focus:border-orange-500"
                        )}
                        placeholder="e.g., VEND001"
                        required
                        disabled={!!vendor}
                    />
                    {idError && <span className="text-xs text-red-600 mt-1">{idError}</span>}
                    {isAutoGenerated && !idError && <span className="text-xs text-green-600 mt-1">Auto-generated based on vendor name</span>}
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Vendor Name *</label>
                    <div className="relative">
                        <Building size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                        <input
                            type="text"
                            value={form.vendorName}
                            onChange={e => handleVendorNameChange(e.target.value)}
                            className="w-full pl-9 pr-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                            placeholder="e.g., ABC Distributors"
                            required
                            disabled={!!vendor}
                        />
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Primary Mobile *</label>
                    <div className="relative">
                        <Phone size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                        <input
                            type="tel"
                            value={form.mobileNumber}
                            onChange={e => handleChange('mobileNumber', e.target.value)}
                            className="w-full pl-9 pr-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                            placeholder="e.g., 9876543210"
                            required
                        />
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Email</label>
                    <div className="relative">
                        <Mail size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                        <input
                            type="email"
                            value={form.email}
                            onChange={e => handleChange('email', e.target.value)}
                            className="w-full pl-9 pr-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                            placeholder="e.g., vendor@example.com"
                        />
                    </div>
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Secondary Mobile</label>
                    <div className="relative">
                        <Phone size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                        <input
                            type="tel"
                            value={form.secondaryNumber}
                            onChange={e => handleChange('secondaryNumber', e.target.value)}
                            className="w-full pl-9 pr-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                            placeholder="e.g., 9876543210"
                        />
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">GST Number</label>
                    <input
                        type="text"
                        value={form.gstNo}
                        onChange={e => handleChange('gstNo', e.target.value)}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                        placeholder="e.g., 27AABCU1234H1Z0"
                    />
                </div>
            </div>

            <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Address</label>
                <div className="relative">
                    <MapPin size={16} className="absolute left-3 top-3 text-slate-400" />
                    <textarea
                        value={form.address}
                        onChange={e => handleChange('address', e.target.value)}
                        className="w-full pl-9 pr-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:border-orange-500"
                        placeholder="e.g., 123 Business Street, City, State, Pin"
                        rows="3"
                    />
                </div>
            </div>

            <div className="flex gap-3 pt-2">
                <button
                    type="button"
                    onClick={onCancel}
                    className="flex-1 px-4 py-2 border border-slate-200 rounded-lg text-slate-600 hover:bg-slate-50 text-sm font-medium"
                    disabled={saving}
                >
                    Cancel
                </button>
                <button
                    type="submit"
                    className="flex-1 px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded-lg text-sm font-medium disabled:opacity-50"
                    disabled={saving}
                >
                    {saving ? 'Saving...' : vendor ? 'Update Vendor' : 'Add Vendor'}
                </button>
            </div>
        </form>
    );
};

// Vendor Table Component
import { useAuth } from '../context/AuthContext';

export const VendorTable = ({ vendors, onEdit, onDelete, loading }) => {
    const { hasPermission } = useAuth();
    if (loading) {
        return <div className="px-6 py-12 text-center text-slate-400">Loading vendors...</div>;
    }

    if (!vendors || vendors.length === 0) {
        return <div className="px-6 py-12 text-center text-slate-400">No vendors found. Create your first vendor to get started.</div>;
    }

    return (
        <div className="overflow-x-auto">
            <table className="w-full">
                <thead className="bg-slate-50 border-b border-slate-200">
                    <tr>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Vendor ID</th>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Vendor Name</th>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Mobile</th>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Email</th>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">GST No</th>
                        <th className="px-6 py-3 text-left text-xs font-semibold text-slate-600 uppercase">Address</th>
                        <th className="px-6 py-3 text-center text-xs font-semibold text-slate-600 uppercase">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {vendors.map((vendor, idx) => (
                        <tr key={vendor.vendorId || idx} className="border-b border-slate-50 hover:bg-slate-50/50">
                            <td className="px-6 py-4 font-mono text-sm text-slate-700 font-medium">{vendor.vendorId || '-'}</td>
                            <td className="px-6 py-4 font-medium text-slate-700">{vendor.vendorName || vendor.Name || '-'}</td>
                            <td className="px-6 py-4 text-slate-600">{vendor.mobileNumber || '-'}</td>
                            <td className="px-6 py-4 text-slate-600">{vendor.email || '-'}</td>
                            <td className="px-6 py-4 text-slate-600 text-sm">{vendor.gstNo || '-'}</td>
                            <td className="px-6 py-4 text-slate-600 text-sm max-w-xs truncate">{vendor.address || '-'}</td>
                            <td className="px-6 py-4">
                                <div className="flex justify-center gap-3">
                                    {hasPermission('edit_vendor') && (
                                        <button
                                            onClick={() => onEdit(vendor)}
                                            className="text-blue-500 hover:text-blue-700 text-sm font-medium"
                                            title="Edit"
                                        >
                                            Edit
                                        </button>
                                    )}
                                    {hasPermission('delete_vendor') && (
                                        <button
                                            onClick={() => onDelete(vendor)}
                                            className="text-red-500 hover:text-red-700 text-sm font-medium"
                                            title="Delete"
                                        >
                                            Delete
                                        </button>
                                    )}
                                </div>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};
