extend type Mutation {
  """
  ✨ Insert a single `Machine` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machine_insert(
    """
    Data object to insert into the table.
    """
    data: Machine_Data!
  ): Machine_KeyOutput! @fdc_generated(from: "Machine", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `MachineInventory` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machineInventory_insert(
    """
    Data object to insert into the table.
    """
    data: MachineInventory_Data!
  ): MachineInventory_KeyOutput! @fdc_generated(from: "MachineInventory", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `MachineStockAssignment` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machineStockAssignment_insert(
    """
    Data object to insert into the table.
    """
    data: MachineStockAssignment_Data!
  ): MachineStockAssignment_KeyOutput! @fdc_generated(from: "MachineStockAssignment", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Product` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  product_insert(
    """
    Data object to insert into the table.
    """
    data: Product_Data!
  ): Product_KeyOutput! @fdc_generated(from: "Product", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PurchaseOrder` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  purchaseOrder_insert(
    """
    Data object to insert into the table.
    """
    data: PurchaseOrder_Data!
  ): PurchaseOrder_KeyOutput! @fdc_generated(from: "PurchaseOrder", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PurchasedProduct` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  purchasedProduct_insert(
    """
    Data object to insert into the table.
    """
    data: PurchasedProduct_Data!
  ): PurchasedProduct_KeyOutput! @fdc_generated(from: "PurchasedProduct", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `RefillLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  refillLog_insert(
    """
    Data object to insert into the table.
    """
    data: RefillLog_Data!
  ): RefillLog_KeyOutput! @fdc_generated(from: "RefillLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Sale` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sale_insert(
    """
    Data object to insert into the table.
    """
    data: Sale_Data!
  ): Sale_KeyOutput! @fdc_generated(from: "Sale", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Vendor` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  vendor_insert(
    """
    Data object to insert into the table.
    """
    data: Vendor_Data!
  ): Vendor_KeyOutput! @fdc_generated(from: "Vendor", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `VendorPurchase` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  vendorPurchase_insert(
    """
    Data object to insert into the table.
    """
    data: VendorPurchase_Data!
  ): VendorPurchase_KeyOutput! @fdc_generated(from: "VendorPurchase", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `WarehouseInventory` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  warehouseInventory_insert(
    """
    Data object to insert into the table.
    """
    data: WarehouseInventory_Data!
  ): WarehouseInventory_KeyOutput! @fdc_generated(from: "WarehouseInventory", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Machine` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machine_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Machine_Data!]!
  ): [Machine_KeyOutput!]! @fdc_generated(from: "Machine", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `MachineInventory` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machineInventory_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [MachineInventory_Data!]!
  ): [MachineInventory_KeyOutput!]! @fdc_generated(from: "MachineInventory", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `MachineStockAssignment` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  machineStockAssignment_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [MachineStockAssignment_Data!]!
  ): [MachineStockAssignment_KeyOutput!]! @fdc_generated(from: "MachineStockAssignment", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Product` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  product_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Product_Data!]!
  ): [Product_KeyOutput!]! @fdc_generated(from: "Product", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PurchaseOrder` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  purchaseOrder_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PurchaseOrder_Data!]!
  ): [PurchaseOrder_KeyOutput!]! @fdc_generated(from: "PurchaseOrder", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PurchasedProduct` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  purchasedProduct_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PurchasedProduct_Data!]!
  ): [PurchasedProduct_KeyOutput!]! @fdc_generated(from: "PurchasedProduct", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `RefillLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  refillLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [RefillLog_Data!]!
  ): [RefillLog_KeyOutput!]! @fdc_generated(from: "RefillLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Sale` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sale_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Sale_Data!]!
  ): [Sale_KeyOutput!]! @fdc_generated(from: "Sale", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Vendor` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  vendor_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Vendor_Data!]!
  ): [Vendor_KeyOutput!]! @fdc_generated(from: "Vendor", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `VendorPurchase` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  vendorPurchase_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [VendorPurchase_Data!]!
  ): [VendorPurchase_KeyOutput!]! @fdc_generated(from: "VendorPurchase", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `WarehouseInventory` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  warehouseInventory_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [WarehouseInventory_Data!]!
  ): [WarehouseInventory_KeyOutput!]! @fdc_generated(from: "WarehouseInventory", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Machine` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Machine`.
  """
  machine_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Machine_Data!
  ): Machine_KeyOutput! @fdc_generated(from: "Machine", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `MachineInventory` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MachineInventory`.
  """
  machineInventory_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: MachineInventory_Data!
  ): MachineInventory_KeyOutput! @fdc_generated(from: "MachineInventory", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `MachineStockAssignment` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MachineStockAssignment`.
  """
  machineStockAssignment_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: MachineStockAssignment_Data!
  ): MachineStockAssignment_KeyOutput! @fdc_generated(from: "MachineStockAssignment", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Product` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Product`.
  """
  product_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Product_Data!
  ): Product_KeyOutput! @fdc_generated(from: "Product", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PurchaseOrder` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PurchaseOrder`.
  """
  purchaseOrder_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PurchaseOrder_Data!
  ): PurchaseOrder_KeyOutput! @fdc_generated(from: "PurchaseOrder", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PurchasedProduct` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PurchasedProduct`.
  """
  purchasedProduct_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PurchasedProduct_Data!
  ): PurchasedProduct_KeyOutput! @fdc_generated(from: "PurchasedProduct", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `RefillLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `RefillLog`.
  """
  refillLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: RefillLog_Data!
  ): RefillLog_KeyOutput! @fdc_generated(from: "RefillLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Sale` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Sale`.
  """
  sale_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Sale_Data!
  ): Sale_KeyOutput! @fdc_generated(from: "Sale", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Vendor` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Vendor`.
  """
  vendor_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Vendor_Data!
  ): Vendor_KeyOutput! @fdc_generated(from: "Vendor", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `VendorPurchase` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `VendorPurchase`.
  """
  vendorPurchase_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: VendorPurchase_Data!
  ): VendorPurchase_KeyOutput! @fdc_generated(from: "VendorPurchase", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `WarehouseInventory` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WarehouseInventory`.
  """
  warehouseInventory_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: WarehouseInventory_Data!
  ): WarehouseInventory_KeyOutput! @fdc_generated(from: "WarehouseInventory", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Machine` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Machine`.
  """
  machine_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Machine_Data!]!
  ): [Machine_KeyOutput!]! @fdc_generated(from: "Machine", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `MachineInventory` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MachineInventory`.
  """
  machineInventory_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [MachineInventory_Data!]!
  ): [MachineInventory_KeyOutput!]! @fdc_generated(from: "MachineInventory", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `MachineStockAssignment` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MachineStockAssignment`.
  """
  machineStockAssignment_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [MachineStockAssignment_Data!]!
  ): [MachineStockAssignment_KeyOutput!]! @fdc_generated(from: "MachineStockAssignment", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Product` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Product`.
  """
  product_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Product_Data!]!
  ): [Product_KeyOutput!]! @fdc_generated(from: "Product", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PurchaseOrder` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PurchaseOrder`.
  """
  purchaseOrder_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PurchaseOrder_Data!]!
  ): [PurchaseOrder_KeyOutput!]! @fdc_generated(from: "PurchaseOrder", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PurchasedProduct` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PurchasedProduct`.
  """
  purchasedProduct_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PurchasedProduct_Data!]!
  ): [PurchasedProduct_KeyOutput!]! @fdc_generated(from: "PurchasedProduct", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `RefillLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `RefillLog`.
  """
  refillLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [RefillLog_Data!]!
  ): [RefillLog_KeyOutput!]! @fdc_generated(from: "RefillLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Sale` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Sale`.
  """
  sale_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Sale_Data!]!
  ): [Sale_KeyOutput!]! @fdc_generated(from: "Sale", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Vendor` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Vendor`.
  """
  vendor_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Vendor_Data!]!
  ): [Vendor_KeyOutput!]! @fdc_generated(from: "Vendor", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `VendorPurchase` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `VendorPurchase`.
  """
  vendorPurchase_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [VendorPurchase_Data!]!
  ): [VendorPurchase_KeyOutput!]! @fdc_generated(from: "VendorPurchase", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `WarehouseInventory` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WarehouseInventory`.
  """
  warehouseInventory_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [WarehouseInventory_Data!]!
  ): [WarehouseInventory_KeyOutput!]! @fdc_generated(from: "WarehouseInventory", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Machine` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Machine` or `null` if not found.
  """
  machine_update(
    """
    The key used to identify the object.
    """
    key: Machine_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Machine_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Machine_Data!
  ): Machine_KeyOutput @fdc_generated(from: "Machine", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `MachineInventory` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `MachineInventory` or `null` if not found.
  """
  machineInventory_update(
    """
    The key used to identify the object.
    """
    key: MachineInventory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MachineInventory_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: MachineInventory_Data!
  ): MachineInventory_KeyOutput @fdc_generated(from: "MachineInventory", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `MachineStockAssignment` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `MachineStockAssignment` or `null` if not found.
  """
  machineStockAssignment_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MachineStockAssignment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MachineStockAssignment_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: MachineStockAssignment_Data!
  ): MachineStockAssignment_KeyOutput @fdc_generated(from: "MachineStockAssignment", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Product` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Product` or `null` if not found.
  """
  product_update(
    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Product_Data!
  ): Product_KeyOutput @fdc_generated(from: "Product", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PurchaseOrder` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PurchaseOrder` or `null` if not found.
  """
  purchaseOrder_update(
    """
    The key used to identify the object.
    """
    key: PurchaseOrder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PurchaseOrder_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PurchaseOrder_Data!
  ): PurchaseOrder_KeyOutput @fdc_generated(from: "PurchaseOrder", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PurchasedProduct` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PurchasedProduct` or `null` if not found.
  """
  purchasedProduct_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PurchasedProduct_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PurchasedProduct_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PurchasedProduct_Data!
  ): PurchasedProduct_KeyOutput @fdc_generated(from: "PurchasedProduct", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `RefillLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `RefillLog` or `null` if not found.
  """
  refillLog_update(
    """
    The key used to identify the object.
    """
    key: RefillLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: RefillLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: RefillLog_Data!
  ): RefillLog_KeyOutput @fdc_generated(from: "RefillLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Sale` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Sale` or `null` if not found.
  """
  sale_update(
    """
    The key used to identify the object.
    """
    key: Sale_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Sale_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Sale_Data!
  ): Sale_KeyOutput @fdc_generated(from: "Sale", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Vendor` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Vendor` or `null` if not found.
  """
  vendor_update(
    """
    The key used to identify the object.
    """
    key: Vendor_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Vendor_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Vendor_Data!
  ): Vendor_KeyOutput @fdc_generated(from: "Vendor", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `VendorPurchase` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `VendorPurchase` or `null` if not found.
  """
  vendorPurchase_update(
    """
    The key used to identify the object.
    """
    key: VendorPurchase_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VendorPurchase_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: VendorPurchase_Data!
  ): VendorPurchase_KeyOutput @fdc_generated(from: "VendorPurchase", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `WarehouseInventory` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `WarehouseInventory` or `null` if not found.
  """
  warehouseInventory_update(
    """
    The key used to identify the object.
    """
    key: WarehouseInventory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WarehouseInventory_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: WarehouseInventory_Data!
  ): WarehouseInventory_KeyOutput @fdc_generated(from: "WarehouseInventory", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Machine` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  machine_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Machine_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Machine_Data!
  ): Int! @fdc_generated(from: "Machine", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `MachineInventory` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  machineInventory_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: MachineInventory_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: MachineInventory_Data!
  ): Int! @fdc_generated(from: "MachineInventory", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `MachineStockAssignment` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  machineStockAssignment_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: MachineStockAssignment_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: MachineStockAssignment_Data!
  ): Int! @fdc_generated(from: "MachineStockAssignment", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Product` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  product_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Product_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Product_Data!
  ): Int! @fdc_generated(from: "Product", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PurchaseOrder` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  purchaseOrder_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PurchaseOrder_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PurchaseOrder_Data!
  ): Int! @fdc_generated(from: "PurchaseOrder", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PurchasedProduct` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  purchasedProduct_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PurchasedProduct_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PurchasedProduct_Data!
  ): Int! @fdc_generated(from: "PurchasedProduct", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `RefillLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  refillLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: RefillLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: RefillLog_Data!
  ): Int! @fdc_generated(from: "RefillLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Sale` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  sale_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Sale_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Sale_Data!
  ): Int! @fdc_generated(from: "Sale", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Vendor` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  vendor_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Vendor_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Vendor_Data!
  ): Int! @fdc_generated(from: "Vendor", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `VendorPurchase` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  vendorPurchase_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: VendorPurchase_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: VendorPurchase_Data!
  ): Int! @fdc_generated(from: "VendorPurchase", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `WarehouseInventory` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  warehouseInventory_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: WarehouseInventory_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: WarehouseInventory_Data!
  ): Int! @fdc_generated(from: "WarehouseInventory", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Machine` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  machine_delete(
    """
    The key used to identify the object.
    """
    key: Machine_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Machine_FirstRow
  ): Machine_KeyOutput @fdc_generated(from: "Machine", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `MachineInventory` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  machineInventory_delete(
    """
    The key used to identify the object.
    """
    key: MachineInventory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MachineInventory_FirstRow
  ): MachineInventory_KeyOutput @fdc_generated(from: "MachineInventory", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `MachineStockAssignment` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  machineStockAssignment_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MachineStockAssignment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MachineStockAssignment_FirstRow
  ): MachineStockAssignment_KeyOutput @fdc_generated(from: "MachineStockAssignment", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Product` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  product_delete(
    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow
  ): Product_KeyOutput @fdc_generated(from: "Product", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PurchaseOrder` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  purchaseOrder_delete(
    """
    The key used to identify the object.
    """
    key: PurchaseOrder_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PurchaseOrder_FirstRow
  ): PurchaseOrder_KeyOutput @fdc_generated(from: "PurchaseOrder", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PurchasedProduct` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  purchasedProduct_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PurchasedProduct_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PurchasedProduct_FirstRow
  ): PurchasedProduct_KeyOutput @fdc_generated(from: "PurchasedProduct", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `RefillLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  refillLog_delete(
    """
    The key used to identify the object.
    """
    key: RefillLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: RefillLog_FirstRow
  ): RefillLog_KeyOutput @fdc_generated(from: "RefillLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Sale` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  sale_delete(
    """
    The key used to identify the object.
    """
    key: Sale_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Sale_FirstRow
  ): Sale_KeyOutput @fdc_generated(from: "Sale", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Vendor` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  vendor_delete(
    """
    The key used to identify the object.
    """
    key: Vendor_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Vendor_FirstRow
  ): Vendor_KeyOutput @fdc_generated(from: "Vendor", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `VendorPurchase` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  vendorPurchase_delete(
    """
    The key used to identify the object.
    """
    key: VendorPurchase_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VendorPurchase_FirstRow
  ): VendorPurchase_KeyOutput @fdc_generated(from: "VendorPurchase", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `WarehouseInventory` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  warehouseInventory_delete(
    """
    The key used to identify the object.
    """
    key: WarehouseInventory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WarehouseInventory_FirstRow
  ): WarehouseInventory_KeyOutput @fdc_generated(from: "WarehouseInventory", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Machine` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  machine_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Machine_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Machine", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `MachineInventory` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  machineInventory_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: MachineInventory_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "MachineInventory", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `MachineStockAssignment` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  machineStockAssignment_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: MachineStockAssignment_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "MachineStockAssignment", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Product` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  product_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Product_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Product", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PurchaseOrder` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  purchaseOrder_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PurchaseOrder_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PurchaseOrder", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PurchasedProduct` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  purchasedProduct_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PurchasedProduct_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PurchasedProduct", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `RefillLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  refillLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: RefillLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "RefillLog", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Sale` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  sale_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Sale_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Sale", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Vendor` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  vendor_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Vendor_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Vendor", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `VendorPurchase` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  vendorPurchase_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: VendorPurchase_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "VendorPurchase", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `WarehouseInventory` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  warehouseInventory_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: WarehouseInventory_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "WarehouseInventory", purpose: DELETE_MULTIPLE)
}
